config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get '/search', to: "tasks#search", as: "search_tasks"
  resources :tasks
  # patch "/admin/users/:id", to: "admin/users#update", as: "admin_users"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    validates :name, :content, presence: true
    scope  :order_by_created_at, ->  {order(created_at: :desc)}
    scope  :order_by_deadline,  ->  {order(expiry_date: :desc)}
    scope  :order_by_priority_button,  ->  {order(priority: :desc)}
    scope  :order_by_priority,  ->  (priority){where(priority: priority)}
    scope :label_search, -> (search_label){
        tasks = Labeling.where(label_id: search_label)
        ids = tasks.map{ |task| task.task_id } 
        where(id: ids)
    }
    scope  :order_by_status,  ->  (status){where(status: status)}
    scope  :title_search, -> (search_key){where("name LIKE ?","%#{search_key}%")}
    scope :kaminari, -> (kaminari_pages){page(kaminari_pages).per(5)}
  
    paginates_per 50
    enum status: {
        unstarted: 0,
        progress: 1,
        completed: 2
    }
    enum priority: {
        Low: 0,
        Medium:1,
        High: 2
    }
    belongs_to :user, optional: true
    has_many :labelings, dependent: :destroy
    has_many :labels, through: :labelings, source: :label
    
    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  

  # GET /tasks or /tasks.json
  def index

    @tasks = current_user.tasks.all.page(params[:page]).per(5)
    @tasks = current_user.tasks.all.order_by_deadline.page(params[:page]).per(5) if params[:sort_expired] == "true"
    @tasks = current_user.tasks.all.order_by_priority_button.page(params[:page]).per(5) if params[:sort_by_priority] == "true"

    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))

  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new  
    @labels = Label.all
  end

  # GET /tasks/1/edit
  def edit
    @labels = Label.all
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)
    @task.status=params[:task][:status]  
    @task.priority=params[:task][:priority]
    
    
    
      if @task.save
        redirect_to @task, notice: "Task was successfully created." 
      else
        redirect_to new_task_path, notice: "task not created"
      end
    
  end

  def search 
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    session[:search] = {'name' => params[:search_title], 'status' => params[:search_status], 'priority' => params[:search_priority]}
   
    if params[:search_title].present?
      if params[:search_status].present?
        if params[:search_priority].present?
          if params[:search_label].present?
          @tasks = current_user.tasks.title_search(params[:search_title]).order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).label_search(params[:search_label]).kaminari params[:page] 
          else 
            @tasks = current_user.tasks.title_search(params[:search_title]).order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).kaminari params[:page] 
          end
        else
          @tasks = current_user.tasks.title_search(params[:search_title]).order_by_status(params[:search_status]).kaminari params[:page] 
        end
      elsif params[:search_priority].present?
        @tasks = current_user.tasks.title_search(params[:search_title]).order_by_priority(params[:search_priority]).kaminari params[:page] 
      else
        @tasks = current_user.tasks.title_search(params[:search_title]).kaminari params[:page] 

      end


    elsif params[:search_status].present?
      
      if params[:search_priority].present?
        if params[:search_label].present?
          @tasks = current_user.tasks.order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).label_search(params[:search_label]).kaminari params[:page] 
        else
           @tasks = current_user.tasks.order_by_status(params[:search_status]).order_by_priority(params[:search_priority]).kaminari params[:page]
        end
          
      else
        @tasks = current_user.tasks.order_by_status(params[:search_status]).kaminari params[:page] 
      end

      
    elsif params[:search_priority].present?
      
      if params[:search_status].present?
        if params[:search_label].present?
          @tasks = current_user.tasks.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).label_search(params[:search_label]).kaminari params[:page]
        else
          @tasks = current_user.tasks.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).kaminari params[:page] 
        end
        
      else
        @tasks = current_user.tasks.order_by_priority(params[:search_priority]).kaminari params[:page] 
      end


    elsif params[:search_label].present?
      
      if params[:search_status].present?
        if params[:search_priority].present?
          @tasks = current_user.tasks.order_by_priority(params[:search_priority]).order_by_status(params[:search_status]).label_search(params[:search_label]).kaminari params[:page]
        else
          @tasks = current_user.tasks.label_search(params[:search_label]).order_by_status(params[:search_status]).kaminari params[:page] 
        end
        
      else
        @tasks = current_user.tasks.label_search(params[:search_label]).kaminari params[:page] 
      end
      
    else
      @tasks = current_user.tasks
    end
  
    # @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    
    render :index
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :content, :status, :priority, :expiry_date, label_ids: [])
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys %>
  </div>
  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>
  <div class="field form-group">
    <%= form.label :expiry_date %>
    <%= form.datetime_select :expiry_date %>
  </div>
  <h4>Labels</h4>
 
  
     <div class="row">
      <% @labels.each do |label| %>
      <div class="col m-3 col-lg-2">
          <p>
            <%= form.check_box :label_ids, { multiple: true, checked: @task.labels.find_by(id: label.id).present?,  disabled: label[:disabled], include_hidden: false }, label[:id] %>
          <%=form.label :label_ids, label.name,value:label[:id],style:'text-decoration:none'%>
          </p>
        </div>
     <% end %>

   

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>General Tasks List</h1>

<div class="row py-3">
  <div class="col sm-3">
    <div class="col">
      
      <%= form_with(url: search_tasks_path, method: :get, local: true) do |f| %>
      <% if defined? @search_title %>
        <%= f.text_field :search_title, value: @search_title ,class:'label mx-3',style:'height:40px;width:200px'%>
      <% else %>
        <%= f.text_field :search_title %>
      <% end %>
        <%= f.select :search_status, Task.statuses.map { |k, v| [k, v] }, class: 'search_status form-control', prompt: 'status'%>
        <%= f.select :search_priority, Task.priorities.map { |k, v| [k, v] }, class: 'search_priority form-control', prompt: 'priority'%>
        
        <%= f.select :search_label, @labels.collect { |p| [p.name, p.id]}, class: "search_label", prompt: 'Tag' %>
        <%= f.submit 'search' ,class:'btn btn-light'%>

      
      <% end %>
    </div>
  </div>
</div>
<%= link_to "sort by end deadline", tasks_path(sort_expired: "true") ,class: 'col btn btn-secondary text-light'%>
  <%= link_to "sort by priority", tasks_path(sort_by_priority: "true") ,class: 'col btn btn-secondary text-light'%>

<%= link_to 'New Task', new_task_path, class: "btn btn-primary" %>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Deadline </th>
      <th>Created At</th>
      <th>Status</th>
      <th>Priority</th>
      <th>Author</th>
      <th>Labels</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.expiry_date %></td>
        <td><%= task.created_at %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= task.user.name %></td>
        <td>
          <%task.labels.all.each do |label|%>
          <%= label.name%> <br>
          <%end%>
        </td>
        <td><%= link_to 'Show', task , class: 'btn btn-outline-primary'%> 
          <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-outline-success' %>
          <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<%= notice %>
<h1>New Task</h1>

<%= render 'form', task: @task %>
<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>