config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get '/search', to: "tasks#search", as: "search_tasks"
  resources :tasks
  # patch "/admin/users/:id", to: "admin/users#update", as: "admin_users"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    before_validation {email.downcase!}
    validates :email, presence: true, uniqueness: true, length: {maximum: 255}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  }
    validates :password, presence: true, length: {minimum:6}
    has_many :tasks
    # before_create do self.is_admin = true
    end


app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [ :new, :create]
  # before_action :is_admin, only: [:update, :show, :destory]

  # def is_admin
  #    redirect_to admin_users_path if current_user.is_admin==true
     
  # end

  def index
      @users = User.all.where.not(id: current_user.id)
  end
  
  def show
      redirect_to tasks_path, notice: 'only the administrator can access it' if current_user.is_admin != true
      
  end

  def new
    if current_user&.is_admin 
      @user = User.new
    elsif current_user ==nil
      @user = User.new
    else
      redirect_to tasks_path
    end
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    
    respond_to do |format|
      if @user.save
        if current_user == nil 
          session[:user_id] = @user.id
        end
        format.html { redirect_to tasks_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Changed user information" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  skip_before_action :login_required, only: [ :new, :create]
  def index 
    @users = User.all
  end
  def show
    if current_user != @user
      redirect_to tasks_path
    else
    @tasks = @user.tasks.all.page(params[:page]).per(2)
    end
  end

  def new
    if current_user&.is_admin 
      @user = User.new
    elsif current_user ==nil
      @user = User.new
    else
      redirect_to tasks_path
    end
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to tasks_path, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Changed user information" }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :is_admin)
  end
 
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_footer.html.erb
<footer>
    <p> Chabla tech &copy; 2021 Chabla App</p>
</footer>

app/views/admin/users/_form.html.erb

<%= form_with(model: [:admin, user], local: true) do |form| %>
  <% if
  user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(user.errors.count, "error") %> prohibited this user from being
      saved:
    </h2>
  
    <ul>
      <% user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="field">
    <%= form.label :name %> <%= form.text_field :name , class: "form-control"%>
  </div>
  <div class="field">
    <%= form.label :email %> <%= form.email_field :email , class: "form-control"%>
  </div>
  
  <div class="field">
    <%= form.label :password %> <%= form.password_field :password , class:
    "form-control"%>
  </div>
  <div class="field">
    <%= form.label :password_confirmation %> <%=
    form.password_field:password_confirmation , class: "form-control"%>
  </div>
  <%if current_user and current_user.is_admin%>
  <div class="field my-2">
    <%= form.label "make admin"%>
    <%= form.check_box :is_admin %>
  </div>
  <%end%>
  
  <% if action_name == "edit" %>
  <div class="actions" style="float: right"><%= form.submit "Update" %></div>
  <% else %>
  <div class="actions" style="float: right"><%= form.submit "Signup" %></div>
  
  <% end %> <% end %>
  

app/views/admin/users/_header.html.erb
<header>
    <nav class="navbar navbar-light bg-light p-3">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">Instagram Clone App</span>
            <% if logged_in? %>
            <div class="">

                <%= link_to 'View all posts', posts_path , class: "btn btn-outline-secondary"%>
                <%= link_to 'Publish', new_post_path , class: "btn btn-outline-primary"%>
            </div>
            <div>
                <%= link_to "Profile", user_path(current_user.id) , class: "btn btn-primary text-light"%>
                <%= link_to "Logout", session_path(current_user.id), method: :delete , class: "btn btn-danger text-light" %>
            </div>
            <% else %>
            <div>

                <%= link_to "Sign up", new_user_path , class: "btn btn-outline-primary mx-3", style: "float: right;" %>
                <%= link_to "Login", new_session_path, class: "btn btn-success text-light" %>

            </div>
            <% end %>
        </div>
    </nav>
</header>

app/views/admin/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %> 
<%= link_to 'Show', edit_admin_user_url(@user),class: "btn btn-outline-warning"%> | 
<%= link_to 'Back', admin_users_path, class: "btn btn-outline-danger" %>

app/views/admin/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
      <th>Task count</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
      <td>
        <%= link_to 'Destroy', admin_user_path(user), method: :delete, data: {
        confirm: 'Are you sure?' } %>
      </td>
      <td style="padding-left: 30px"><%=user.tasks.count%></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container text-center">
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  
  <% if current_user.is_admin %>
    <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-warning" %>
  <% end %>
  
   | <%=
  link_to 'Back', tasks_path , class: "btn btn-danger"%>
</div>