config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get '/search', to: "tasks#search", as: "search_tasks"
  resources :tasks
  # patch "/admin/users/:id", to: "admin/users#update", as: "admin_users"
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Everleaf</title>
    <%= csrf_meta_tags %> <%= csp_meta_tag %> 
    <%= stylesheet_link_tag'application', media: 'all', 'data-turbolinks-track': 'reload' %> 
    <%=javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light bg-light p-3">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1">Every Leaf App</span>
          <% if logged_in? %>

          <div>
            <%= link_to "Manage", admin_users_path , class: "btn btn-primary text-light"%>
             <%= link_to "Profile", user_path(current_user.id) , class: "btn btn-primary text-light"%>
            <%= link_to "Logout", session_path(current_user.id), method: :delete, class: "btn btn-danger text-light", data:{ confirm: 'are you sure ?'} %>
          </div>
          <% else %>
          <div>
            <%= link_to "Sign up", new_admin_user_path , class: "btn btn-outline-primary mx-3", style: "float: right;" %> 
            <%= link_to "Login", new_session_path, class: "btn btn-success text-light" %>
          </div>
          <% end %>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>